databases:
  - name: mancoba
    databaseName: mancoba
    user: mancoba_user

services:
  - type: web
    name: recipe-app-prod
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mancoba
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false